### ISSUE TITLE
How to construct a second page ?

### ISSUE THREAD

**Issue by malosaa** [psibean/discord.js-pagination#12]
i did see this example,

```
const pages = [];
for (let i = 0; i 10; i++) {
  const pageEmbed = new MessageEmbed();
  pageEmbed
    .setTitle(`This embed is index ${i}!`)
    .setDescription(`That means it is page #${i + 1}`);
  pages.push(pageEmbed);
}
```

how to create page nr 2

regards

**Comment by psibean** [comment]
Hey, the code example you have referenced is actually creating 10 pages. Not just 1 or 2. You can create your embeds anyway you like, all that you need in the end is an array of embeds!

A loop may not work if your pages don't share a common data source. For example, you might have some data like this:

```
const data = [
    {
        message: "Some text for page one",
        image: "http://someimageurl.com/example.png"
    },
    {
        message: "Some other text for page two",
        image: "http://someotherurl.com/example.png"
    }
]
```

And you could create an array of embeds:

```
const pages = [];
for (let i = 0; i < data.length; i++) {
    const embed = new MessageEmbed().setTitle(`Page number ${i + 1}`).setDescription(data[i].message).setImage(data[i].image));
     pages.push(embed);
}
```

And it will loop both of the items in the data array and create an embed for each one and put them in the pages array. You create your second embed the same way you create your first one. It doesn't need to be a loop though.

You could do:

```
const pageOne = new MessageEmbed();
const pageTwo = new MesssageEmbed();
// Omitting the setTitle, description, etc 
const pages = [pageOne, pageTwo];
```

How you create your pages is entirely up to you, and depends on your use case, all you need is an array of embeds.

I'm happy to help and support and I do not intend or mean to be patronising, but the question is an indicator that you're a bit short on some fundamental programming concepts, so I'm going to recommend you check out /r/learnjavascript and maybe start with some simpler things. I'd recommend you familiarise yourself with (and understand) the technical terminology. E.g. parameters vs arguments, signatures vs calls, declaration vs assignment and re-assignment, scope, closures, etc.

**Comment by psibean** [comment]
Are you still struggling with this? I'll close the issue if you're all good.

**Comment by malosaa** [comment]
> Are you still struggling with this? I'll close the issue if you're all good.

sorry for the late reply, no i'm good. 
I did find a other way to do this aswell. 

Many thanks for the reply. regards
